### ISSUE TITLE
[Bug] forum logo and users avatars are breaking after they are published in the topics

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#1079]
![DT profile](https://user-images.githubusercontent.com/72157778/97811963-2a450700-1c8f-11eb-9541-b0d2880ebb83.png)
Link to the profile: https://coinbistro.com/profiles/DefaultTrustList

Steps:
- copy the avatar's URL;
- go to some topic;
- place the avatar's URL in the [img] tags.

Some time later after these actions (0-60 minutes) the user's avatar will be unavailable.

See the GIF how to get this bug: https://i.imgur.com/NlR5u6R.gif

**Comment by akinsey** [comment]
Nice find, we will look into this!

**Comment by Rizzrack09** [comment]
It's not fixed yet...
Veleor:
`Today I tested the bug with the forum logo again (issue #1079). But this time it didn't break for some reason.`
`So I tried this glitch on your avatar and it worked!`
`Perhaps the Coinbistro logo doesn't break now, since the exact same picture URL is placed in kkid's avatar, or because this picture has been posted several times in a row in different topics`

@akinsey could this have anything to do with image_expirations not working properly?
