### ISSUE TITLE
[Bug] issues with links that have numbers in slug

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#1084]
Sample: `https://github.com/epochtalk/epochtalk/issues/542`

If you put such link in [url] tag, then this link becomes invalid, since the extra prefix "https//" will be automatically added to it: [LINK](https://https//github.com/epochtalk/epochtalk/issues/542)

Also, such links can't add in user's profile, to the "Website" column.

**Comment by Rizzrack09** [comment]
Example in post: https://coinbistro.com/threads/2381b396-0c80-405b-91ce-71143a27ae68/posts?start=114#OKg13xRHTOSwfACpVmyL8A
In the user profile - website field the issue is when adding the number after the .com 
`http://github.com/issues/123` cannot be added "Profile could not be updated"
`http://github123.com/issues` works... I mean can be added in the field

**Comment by akinsey** [comment]
Will fix, thanks for the report
