### ISSUE TITLE
S3 not configured is a goddamn lie

### ISSUE THREAD

**Issue by wangbus** [epochtalk/epochtalk#118]
@unenglishable is our savior and will point us to the truth! :shipit:

**Comment by unenglishable** [comment]
This was originally console logging "undefined"; yes, I found it.  The error is coming from `server/images/s3.js` (the last line in the file).  `s3.initClient()` is being called, with no input, which causes the authentication to fail.  However, it appears this method is not even the one being used to authenticate the server.  Basically, it's deprecated.

Please make sure this method is removed or instantiated correctly, or whatever the hell you need to.  It doesn't even do anything, because s3 is still configured correctly through `app/services/s3ImageUpload.js` (probably).

Thanks for reading!

**Comment by taesup** [comment]
@unenglishable As my most disliked ICS professor would say, "you must read the code more." ```s3.initClient()``` is fine to call without arguments. It defaults to the values stored in the configs. The authentication is not failing. Nothing is wrong here other than the rejection in the first promise being printed out. Thus, the original 'undefined'. 

Also, ```app/services/s3ImageUpload.js``` does not configure s3. It just uses the file previously mentioned. 

The real issue is that ```s3.initClient()``` is called whether or not s3 is the chosen image host. A simple if statement fixes that. I've fixed it in my branch for rate limiting. 

... so yea, nothing to see here. Move along.

**Comment by unenglishable** [comment]
taken care of, somewhere
