### ISSUE TITLE
Watch fails

### ISSUE THREAD

**Issue by hipio** [epochtalk/epochtalk#180]
The watcher throw an error when using `npm run serve`, even with a clean install.

The easiest fix I've found is changing the variable `nmPath` in `scripts/tasks/watching.js` from: 

    var nmPath = path.normalize(__dirname + '/../../modules/node_modules'); 

into 

    var nmPath = path.normalize(__dirname + '/../../modules');`.

I've also removed `epochtalk-core-pg` from the watcher list as it's a `node_module` and doesn't need to be watched (as no changed should be made here).

**Comment by akinsey** [comment]
Thanks for the issue, nice catch!  This should be resolved with the commit above. 

We are now watching the local modules within `/modules` instead of looking in `/modules/node_modules`.

We do watch `epochtalk-core-pg` for development purposes, but we've updated the path to look in `/node_modules` instead of `/modules/node_modules`. This is useful in the case that you symlink `epochtalk-core-pg` in your `/node_modules` folder for development.
