### ISSUE TITLE
improve username validation

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#200]
users can currently have names that end with multiple periods `user...`, only contain special characters `._-.-.______...__--`

this limits our implementation of the mentions system, as a user mentioning another user may at times end their sentence with the user's mention and a period.

`That was so cool @unenglishable.`  If an end period is a valid character in a username, the entire name "`@unenglishable.`" would be considered as a user rather than "`@unenglishable`."

**Comment by Minifrij** [comment]
For the sake of backwards compatibility with Bitcointalk it would probably best to not try and prevent certain usernames from being used.  
Perhaps a separate BBCode tag could be used to allow users to tag each other in posts, rather than using the @ symbol (as this could cause other problems if done improperly). [tag] would be the obvious option, or [notify] or something.

**Comment by unenglishable** [comment]
the semantics of (@) mentions in general is limiting.  the nature of an @ mention limits what written text can look like, as well as what a username looks like.

in a forum setting, it may be desirable to display text as freely as possible, allowing users to express their opinions in the way they would like

with that in mind, we may want to use a more formal definition, which requires less guessing at where a mention is -- at least some system that uses an open and close tag.

will be bringing this back up in discussions

**Comment by Minifrij** [comment]
Even if not using full BBCode tags the same effect could be achieved by having the user put a leading @ after the tag name, similar to how a BBCode tag would work (@username@). It wouldn't be conventional, however it would allow for easy tagging while minimizing errors and maintaining backwards compatibility.  

In addition this brings up a number more options in order to try and prevent such cases as described in the OP from happening, for example a form of syntax checking in which the system searches within these @s prior to posting and notifies the author if an account under the username inputted doesn't exist.
