### ISSUE TITLE
"posts by" view contains posts from private boards

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#213]
posts by a user in a board that is viewable only by users with higher role priorities can be seen by any user in the "posts by" view.

**Comment by akinsey** [comment]
I noticed that this only applies when the viewable by option is only set on the category containing the board.

d9e54b704fa7ada510a0db1fdc6f7c6e49e626b0 introduces a temporary fix for this issue. In short, when setting a categories viewable by option, that same option is applied to all nested boards. 

By doing this the expected behavior is achieved and the posts by user page no longer shows posts created by users under a category with higher view access.
