### ISSUE TITLE
ensure correctness of paging algorithms

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#239]
DRY and ensure correctness of paging algorithm

ex:  user invites
single entries are being chopped off

out of 45 total invites...

page 1 returns 25 invites
page 2 returns 19 invites

when comparing the returned results with the table in postgres,
the missing email is between [the last email of page 1] and [the first email of page 2]

if we can write a *correct* paging algorithm, and use it everywhere, we can severely reduce the amount of mistakes made when returning paged data

**Comment by akinsey** [comment]
We should probably split this into two issues. One need to be to fix the issue with the invites paging and another issue should be made and mark as an enhancement for unifying the paging algorithm in the routes. Its more complicated than just using one algorithm though, because paging for our large datasets use a different paging technique. @unenglishable
