### ISSUE TITLE
Post Size Limitations

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#507]
Currently post size is limited to 5000, we can increase it, but what should be the cap? 

Moving issues from #500 into separate issues so we can tackle them one at a time @DdmrDdmrAlt2

**Comment by DdmrDdmrAlt2** [comment]
That should probably need @Theymo’s input. I just created a post, by copying one I created recently on Bitcointalk that bares18820 characters (found some issues I report later). Now considering that Bitcointalk should be migrated at some point to an instance of Epochtalk, the 5K character limit will cause issues, since x amount of posts will only migrate partial content at best.

I don’t know if the 5K characters is a DB restriction (field definition) or UI restriction. If it’s the only latter, migration could succeed, but editing any such post with have the 5K character restriction and be trimmed when saving it.

Ideally, the character limit should be >= Bitcointalk’s character limit per post.

**Comment by akinsey** [comment]
The DB restriction is the same as `text` I believe it's 1GB. It wont be an issue for migrated posts as we are manually adding those to our database, the size restriction only affects things going through our API to create new posts.

I believe it was just arbitrarily capped at 5000 chars. I'll discuss with the team what would be the best size to cap at. Thank you! @DdmrDdmrAlt2

**Comment by DdmrDdmrAlt2** [comment]
Ok cheers. Just bear in mind perhaps that although, as you say, it should not be an issue for the DB content migration, I figure that editing a (currently over) 5K charaters post that was migrated, would likely trim the post back to 5K when saved, thus performing a partial content save upon editing a large migrated post.

**Comment by akinsey** [comment]
Good point! We should cap it at least at whatever it was capped at before then.

**Comment by akinsey** [comment]
Create a setting in the admin panel to set this
