### ISSUE TITLE
Quotes are broken

### ISSUE THREAD

**Issue by CyrusV5** [epochtalk/epochtalk#51]
When quoting, the quoted text shows up under the quote line and sans quote formatation.
In the editor, the quote show fine in the preview.
Example below:
![quotes](https://cloud.githubusercontent.com/assets/4005189/6362891/56859196-bc9a-11e4-86b1-06afb0cdb8dc.PNG)

@taesup

**Comment by taesup** [comment]
So it looks like this issue is due to supporting both the Medium Editor and the BBCode editor at the same time. We already had plans to separate the two out and this is probably going to be the issue that does just that. 

The main problem is that the Medium editor will wrap anything inserted into the contenteditable div with <p> tags. Normally this is fine but when inserting a quote, the first line is capped with the </p> tag. This shifts all the contents of the quote to an html element out the actual quote div element. Thus why the text of the quote is always outside the quote itself.

This issue really only becomes a problem when there are multiple quotes in the editor or if there is a new paragraph before the quote. That new paragraph is what starts the <p> tag that screws up the quoting. So two quotes, one right after the other with no newlines in between work fine but as soon as there's a newline (and the accompanying <p> tag), the quote text is shifted outside the quote div.
