### ISSUE TITLE
[feature] Timezone

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#710]
Users should be able to manually set their own timezone.
Currently server takes into account browser timezone. But many users might use Tor or any VPN but time should still be displayed in local time.
Post: https://coinbistro.com/threads/3AdJStJAQo687Er5bPibSw/posts

**Comment by unenglishable** [comment]
i've been taking a look into solving this issue over the past couple of weeks.  at first, it seemed like a simple feature, but it's actually quite complicated to **correctly** implement and would involve major changes to the way we display dates, as well as minor changes to the way we store and recall date information.

i believe it's accomplishable, but it will a lot of careful work.  i'll be listing implementation details and ideas in this issue's comment thread.

the easiest part, i think, will be the settings interface for picking a timezone.  i believe a +/-HRS GMT/UTC offset could be adequate; although this probably won't work correctly with DST and other inconsistencies within timezones.  it's also possible to use timezone abbreviations, but this would require a library with an accurate and up-to-date list of timezone information.

the main challenge is that browser time is not overridable in the framework we're using (angular).  because of this, there's no simple fix:  we can't just query user settings and set a browser timezone.  my initial approach is to modify the "humanDate" filter, which converts timestamps into human readable dates.  it is possible to specify a timezone to the built-in angular date filter (which our humanDate filter uses).  most dates run through this filter before being shown to the users.

if this is the case, the code for each place where a date is displayed in the app must be individually updated to use the new format of the humanDate filter.  not too difficult, but it also means lots of changes across many modules and files.  furthermore, each place a date is used, we must also query user preferences' timezone.  at the moment, i'm not sure what the best way to do that is; will be checking with @akinsey 

another issue that adds to the complexity arises from converting the date to human readable format.  for example, if a date happens to be "Today", we display the string "Today at (time)" instead of the day and month.  in order to correctly determine if a date is "Today", the queried time and current time must be converted to the user's specified timezone before comparison.


i'm also taking a look into [timezone.js](https://github.com/mde/timezone-js) and [moment.js](momentjs.com/timezone) which could simplify the date conversions when we need to do them.  in code examples i've seen, the browser client runs dates through a custom date-with-timezone constructor before doing any operations on them.  we would still need to update individual code instances, but it would make working with the timezones themselves a little easier.

**Comment by unenglishable** [comment]
just looking for some additional clarification

@Rizzrack09 on macOS, the browser time is set via the OS.  whatever the computer's user selected as their timezone becomes the time displayed in the browser, which is handled independently of any tunneling services.

can you verify that this is not the case for the operating system you (or other users) are using?  (ie, specify an OS/browser pairing where the timezone is set by the user's IP address instead of their OS)

**Comment by Rizzrack09** [comment]
Left Mozilla - Right Tor (running on Windows)
![time zones coinbistro](https://user-images.githubusercontent.com/51131936/71821151-01b5a600-309a-11ea-8c2d-c973b9471176.JPG)
I guess there should be a server side timezone set as GMT. And users would just have a field where to enter the offset +/- X hours.
This is how it looks on bitcointalk (if it helps)
![time offset btt](https://user-images.githubusercontent.com/51131936/71821367-a2a46100-309a-11ea-9e38-f5720ab4618b.JPG)

**Comment by unenglishable** [comment]
@Rizzrack09 thanks for the update 👍 the solution might take a while, but i'll update you when it's ready!

**Comment by unenglishable** [comment]
@Rizzrack09 it's ready 👍
